default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host: <%= ENV["DATABASE_HOST"] || '127.0.0.1' %>
  username: <%= ENV["DATABASE_USER"] || '' %>
  password: <%= ENV["DATABASE_PASS"] || '' %>
  pool: <%= ENV["DATABASE_POOL"] || ENV["RAILS_MAX_THREADS"] || 5  %>
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  reconnect: true

development:
  <<: *default
  database: app_development
test:
  <<: *default
  database: app_test
production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
